name: demo-workflow
run-name: ${{ github.actor }} is a demo for workflow
on:
  push:
    branches: main
  pull_request:
    branches: [ $default-branch ]
  branch_protection_rule:
    types: [created, deleted]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: demo workflow
        run: echo This is a demo workflow for security scan on trigger event - push, pull and create/edit branch protection rule
